### ISSUE TITLE
iOS Camera Permission

### ISSUE THREAD

**Issue by CannyDanny** [ariadnext/React-Native-SmartSDK#3]
In the Usage section specifically in point 3 you are explaining how to handle CAMERA and RECORD_AUDIO permission. However the code handles Android OS only.(If I am not wrong) 
Do you also provide documentation how to handle implementation for iOS permissions ?

**Comment by alain-muller-ariadnext** [comment]
Hello,

you are right: this code is specific to the Android platform. Regarding the iOS platform, you do not have to check permission in advance as it will be requested at runtime when accessing the camera for instance.

You can find the reference from this method in the code here : https://github.com/ariadnext/React-Native-SmartSDK/blob/6434fe605fefd1f3fde2e8a7df8758cea79f8987/ReactIdcheckioClient/index.js#L161 
As you can see, this is only done for the Android platform.

Best Regards,


Alain Muller

**Comment by CannyDanny** [comment]
Thank you for your answer Alain.
